sudo: required
services:
  - docker

before_install:
  - docker build -t ganeshmani009/react-test -f ./cient/Dockerfile.dev ./client

script:
  - docker run ganeshmani009/react-test npm test -- --coverage

after_success:
  - docker build -t ganeshmani009/multi-react ./client  
  - docker build -t ganeshmani009/multi-nginx ./nginx
  - docker build -t ganeshmani009/multi-server ./server
  - docker build -t ganeshmani009/multi-worker ./worker    